### ISSUE TITLE
Parse arguments as Collection of Argument

### ISSUE THREAD

**Issue by khalyomede** [Stillat/blade-parser#10]
Hello and congratulations for v1! I started toying with this package to create a command line which will be able to find out if translation keys have been missing, and can translate them automatically.

I am currently in the process of building the foundation, and the command is able to parse Blade files to search for any calls to `@lang()`, `@choice()`, `trans()`, `__()`, `choice()` functions in the blade file.

Currently if my blade content is this:

```blade
@extends("layout")

@section("content")
  @lang("List of books")
@endsection
```

The blade parser will return this for the "lang" node:

```php
Stillat\BladeParser\Nodes\DirectiveNode {
  +content: "lang"
  +arguments: Stillat\BladeParser\Nodes\ArgumentGroupNode {
    +content: "('List of books')"
  }
}
```

Is it possible to have a list of arguments instead? I think this would avoid having to manually parse the string and use a regex to get the first argument value (which I need to find if the translation key exist or not in the json translation file).

I was thinking of something like this:

```php
Stillat\BladeParser\Nodes\DirectiveNode {
  +content: "lang"
  +arguments: Stillat\BladeParser\Nodes\ArgumentList {
    +count: 1
    +values: array {
      Stillat\BladeParser\Nodes\Argument {
        +content: "List of books"  
      }
    }
  }
}
```

So I could parse and always take the first argument when parsing the `@lang()` to be sure this is the translation key.

Note this is not blocking me for the moment as I will use a regex.

Willing to try to make a PR if you find the idea useful.

**Comment by JohnathonKoster** [comment]
That is a good FR, but definitely gets tricky when people supply JSON content to directives:

```blade
@someDirective({'some': 'value'})
```

or arrays/etc. I'll do some thinking on a way to make it easier to accomplish what you're looking to do for the 90%+ scenarios

**Comment by JohnathonKoster** [comment]
I've added a new `getValues()` helper method to the `ArgumentGroupNode` class in `v1.1.0`. This will split the directive's input string for you (while preserving commas inside strings, arrays, nested structures). It will not automatically unwrap strings, so they will still have their original quotes:

Example:

```php
<?php

use Stillat\BladeParser\Document\Document;

$template = <<<'BLADE'
@extends("layout")

@section("content")
  @lang("arg1", 'arg2', [1,2,3,4,5], ([1,2,3,4), "string,with,commas")
@endsection
BLADE;

$args = Document::fromText($template)
    ->findDirectiveByName('lang')->arguments->getValues();

$args->count(); // 5

$args[0]; // "arg1"
$args[1]; // 'arg2'
$args[2]; // [1,2,3,4,5]
$args[3]; // ([1,2,3,4)
$args[4]; // "string,with,commas"
```
