### ISSUE TITLE
plz release and add to packagist

### ISSUE THREAD

**Issue by tacman** [Stillat/blade-parser#2]
Cool library!  Thanks for releasing it.  Can you please publish a release and add it to packagist?

And then, of course, add installation instructions (composer req ...)

I've added my fork to packagist so I could more easily install it, but I'll delete that to avoid confusion if you could do it.

Thanks again, I was about to start hacking regexes to extract something from blade files, but this works much better!

**Comment by JohnathonKoster** [comment]
@tacman  I'll look into doing that this weekend 🙂

**Comment by JohnathonKoster** [comment]
@tacman 

This is now available on packagist

```
composer require stillat/blade-parser
```

I'll  update documentation this weekend :)
