### ISSUE TITLE
Composer JSON hav'nt PHP mininum version

### ISSUE THREAD

**Issue by rigonlucas** [Stillat/blade-parser#23]
- Suggestion to add minimum version of php to 8.1
- - Use of readonly attribute makes laravel 9.x broken at use
- As apossible: Maybe remove readonly and others new features of php 8.1 attribute of all class can makes package support laravel 9x with php 8.0.
- - It's demand more work :-(

I figure this problem because i still need php 8.0 with laravel 9;x

Greate work with this package!!! Congrats

**Comment by JohnathonKoster** [comment]
Will do in the next release, thank you!

**Comment by JohnathonKoster** [comment]
And done 🤝
