### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by LarsWiegers** [Stillat/blade-parser#27]
Hi, was wondering if you could support laravel 11, the current composer.json requirements from your package don't allow that. 

Examples of how to support it already: https://github.com/LarsWiegers/laravel-translations-checker/pull/46 and https://github.com/LarsWiegers/laravel-maps/pull/50

**Comment by JohnathonKoster** [comment]
I've tagged 1.7, which has updated requirements to allow Laravel 11.

Happy coding!

**Comment by LarsWiegers** [comment]
Thanks @JohnathonKoster
