### ISSUE TITLE
Hangs when parsing 

### ISSUE THREAD

**Issue by tacman** [Stillat/blade-parser#3]
Most files parse fine, but this one gets stuck.

https://raw.githubusercontent.com/themeselection/sneat-html-laravel-admin-template-free/main/resources/views/content/user-interface/ui-navbar.blade.php

This snippet hangs.

```php
        $parser = new Blade();
        $contents = file_get_contents('https://raw.githubusercontent.com/themeselection/sneat-html-laravel-admin-template-free/main/resources/views/content/user-interface/ui-navbar.blade.php');
        $document = $parser->parse($contents);
```

**Comment by tacman** [comment]
This one too:

https://raw.githubusercontent.com/themeselection/sneat-html-laravel-admin-template-free/main/resources/views/content/user-interface/ui-modals.blade.php

**Comment by JohnathonKoster** [comment]
Yea, there is definitely room for performance optimizations with the current state of the parser. I will most likely end up just porting the work here https://github.com/stillat/blade-parser-typescript back to PHP, since it much more optimized.

**Comment by JohnathonKoster** [comment]
@tacman  Out of curiosity - what kind of information are you looking to extract from your templates? If its a small amount of information, I may be able to reduce the scope of a rewrite (and add other features back over time) and tag a new major version that is more optimized

**Comment by tacman** [comment]
I'm working on a blade-to-twig converter, so most of it is just getting
the @ directives.

But I don't think it's a question of optimization, that file is pretty
small, I'm guessing it's a nesting issue, as the only thing that looks
different between it and some others that worked is that there's less
nesting in the HTML.  The actual blade directives are very simple.  At
least that's just my guess.

**Comment by JohnathonKoster** [comment]
Definitely an optimization issue with how it actually traverses the document. If its just the directives, that's a pretty simple thing to improve on. I'll look to do that sometime soon, but don't have any hard timelines as to when I'll be able to get around to it right now 🙂

**Comment by JohnathonKoster** [comment]
I do have a quick fix I'll release this weekend when publishing to packagist, however, to unblock your work :)

**Comment by tacman** [comment]
Thanks!  And if you can look at those two examples, perhaps it is something
easy... (always easier to say when someone else is doing the work!)

If nothing else, do you think it can throw an error (that I can catch),
since right now it completely hangs, so I have to manually exclude files
that don't parse.

Thanks again.

**Comment by JohnathonKoster** [comment]
A quick fix was added to prevent the infinite loop causing this hanging. This has been included with the first tagged release :)

**Comment by PerryRylance** [comment]
I'm seeing this when trying to open Laravel's default `welcome.blade.php` by following the example at https://stillat.com/blade-parser/v1/html-fragments

I haven't gone deep into this - I can just use the TS version - but at a quick glance we are getting to `Document.php`:

`$this->fragments = $fragmentsParser->parse($this->toString());`

And this never completes. I've given it several minutes!

**Comment by JohnathonKoster** [comment]
@PerryRylance  Thanks for letting me know; I will take a look! :)
