### ISSUE TITLE
parsing fails with email addresses

### ISSUE THREAD

**Issue by tacman** [Stillat/blade-parser#5]
<input type="text" id="emailBasic" class="form-control" placeholder="xxxx@xxx.xx">

https://raw.githubusercontent.com/themeselection/sneat-html-laravel-admin-template-free/main/resources/views/content/user-interface/ui-modals.blade.php

Actually, maybe it's not failing, but it's coming back with a "section" as xx, which isn't true.

Ditto with @example.com, as a dummy email

**Comment by JohnathonKoster** [comment]
Its just confused because of the `@` at the beginning there. The current implementation does not support specifying "what" should be a valid directive name.

Will check into filtering out those that don't have whitespace before them, however 👍

**Comment by JohnathonKoster** [comment]
Should be good for those scenarios with `0.0.2` 👍
