### ISSUE TITLE
Str::lcfirst() requires Laravel 9.4 or higher

### ISSUE THREAD

**Issue by pascalbaljet** [Stillat/blade-parser#7]
The `lcfirst` method was introduced in [Laravel 9.4](https://laravel-news.com/laravel-9-4-0). This will cause issues on earlier versions.

https://github.com/Stillat/blade-parser/blob/86680f4dca5a40d40d1c86fafbb701cd13ec7eda/src/Compiler/CompilerServices/CoreDirectiveRetriever.php#L75

**Comment by JohnathonKoster** [comment]
Thanks!

**Comment by JohnathonKoster** [comment]
Refactored in 1.0.1
