### ISSUE TITLE
Error on PHP statements without a closing semicolon (Anticipated PHP compilation error)

### ISSUE THREAD

**Issue by pascalbaljet** [Stillat/blade-parser#9]
Blade supports PHP code without a closing semicolon:

``` blade
@php $counter = 1 @endphp
```

The validator returns this error:
`Anticipated PHP compilation error: [syntax error, unexpected end of file]`

See also:
https://github.com/laravel/framework/blob/0ec445970da249578296796ee0aeefc03813bc23/src/Illuminate/View/Compilers/Concerns/CompilesRawPhp.php#L16

**Comment by JohnathonKoster** [comment]
Currently working as intended. The linked line refers to the compilation behavior of

```blade
@php ($counter = 1)
```

The following will also produce the same resulting PHP:

```php
<?php

use Illuminate\Support\Facades\Blade;

$result = Blade::compileString('@php $counter = 1 @endphp');

```

Example of behavior parity:

https://github.com/laravel/framework/blob/0ec445970da249578296796ee0aeefc03813bc23/tests/View/Blade/BladeVerbatimTest.php#L82

**Comment by JohnathonKoster** [comment]
nvm (shouldn't review when so tired) - spotted the issue

**Comment by JohnathonKoster** [comment]
Corrected in 1.0.3 🙂

**Comment by pascalbaljet** [comment]
Nice! I've found another case that leads to a false positive:

```blade
@php
    if ($someVar) {
        echo 'Yes';
    } else {
        echo 'No';
    }
@endphp
```

**Comment by JohnathonKoster** [comment]
> Nice! I've found another case that leads to a false positive:
> 
> ```
> @php
>     if ($someVar) {
>         echo 'Yes';
>     } else {
>         echo 'No';
>     }
> @endphp
> ```

Is this triggering the `Anticipated PHP compilation error: [syntax error, unexpected end of file]` for you in 1.0.3? If so, are there any other `@php` directives in the template?

I'm have trouble reproducing on the latest version with that template by itself. Thanks!
